plugins/Admin/config/routes.php
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::plugin(
    'Admin',
    ['path' => '/admin'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);

plugins/Admin/src/Model/Table/OrdersTable.php
<?php
namespace Admin\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Orders Model
 *
 * @property \Admin\Model\Table\CompaniesTable|\Cake\ORM\Association\BelongsTo $Companies
 *
 * @method \Admin\Model\Entity\Order get($primaryKey, $options = [])
 * @method \Admin\Model\Entity\Order newEntity($data = null, array $options = [])
 * @method \Admin\Model\Entity\Order[] newEntities(array $data, array $options = [])
 * @method \Admin\Model\Entity\Order|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Admin\Model\Entity\Order patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Admin\Model\Entity\Order[] patchEntities($entities, array $data, array $options = [])
 * @method \Admin\Model\Entity\Order findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class OrdersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('orders');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Companies', [
            'foreignKey' => 'company_id',
            'joinType' => 'INNER',
            'className' => 'Admin.Companies'
        ]);

        $this->hasMany('OrderLines', [
            'foreignKey' => 'order_id',
            'className' => 'Company.OrderLines'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->date('delivery_date')
            ->requirePresence('delivery_date', 'create')
            ->notEmpty('delivery_date');

        $validator
            ->integer('qty')
            ->requirePresence('qty', 'create')
            ->notEmpty('qty');

        $validator
            ->scalar('status')
            ->requirePresence('status', 'create')
            ->notEmpty('status');

        $validator
            ->scalar('remarks')
            ->requirePresence('remarks', 'create')
            ->notEmpty('remarks');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['company_id'], 'Companies'));

        return $rules;
    }
}

plugins/Admin/src/Template/Element/companies_table.ctp
<div class="row">
    <div class="col-sm-7">
        <h5>ENTREPRISES <span class="label label-table label-info"><?= $data->count() ?></span></h5>
    </div>
    <div class="col-sm-2"></div>
    <div class="col-sm-3 text-right">
        <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn waves-effect btn-wj waves-light btn-info"><i class="fa fa-search"></i></button>
            </span>
            <input type="text" id="companies-search"  class="form-control" placeholder="Chercher ...">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table id="companies" class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>DENOMINATION</th>
                <th class="text-center">COMPTE</th>
                <th class="text-center">CARTE</th>
                <th class="text-center">CREDIT</th>
                <th class="text-center">RESERVE</th>
                <th class="text-center">RESERVE CN</th>
                <th class="text-right">ACTIONS</th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($data as $d): ?>
                <tr>


                    <td>
                        <?= $d->id ?>
                    </td>


                    <td>
                        <a href="<?= $this->Url->build(['action'=>'view',$d->id]) ?>" ><?= h(strtoupper($d->denomination)) ?></a>
                    </td>

                    <!-- Statut Compte ( Connexion ) -->
                    <td class="text-center">
                        <?php if($d->user->active): ?>
                            <i class="fa fa-check-square" aria-hidden="true" style="color: #4caf50"></i>
                        <?php else: ?>
                            <i class="mdi mdi-close-box" style="color: red"></i>
                        <?php endif; ?>
                    </td>

                    <!-- Statut Compte ( Paiement ) -->
                    <td class="text-center">
                        <?php if($d->account->allow_card_use): ?>
                            <i class="fa fa-check-square" aria-hidden="true" style="color: #4caf50"></i>
                        <?php else: ?>
                            <i class="mdi mdi-close-box" style="color: red"></i>
                        <?php endif; ?>
                    </td>

                    <!-- CREDIT -->
                    <td class="text-right">
                        <?= number_format(h($d->account->credit), 0, ',', ' ') ?>
                    </td>

                    <!-- RESERVE -->
                    <td class="text-right">
                        <?= number_format(h($d->account->exceeding_allowed_credit), 0, ',', ' ') ?>
                    </td>

                    <td class="text-right">
                        <?= number_format(h($d->account->exceeding_consumption_credit), 0, ',', ' ') ?>
                    </td>


                    <!-- Actions -->
                    <td class="text-right">
                        <a href="<?= $this->Url->build(['action'=>'login',$d->id]) ?>" target="_self" class="btn btn-wj btn-sm">CONNECTER</a>
                        <a href="<?= $this->Url->build(['action'=>'edit',$d->id]) ?>"  class="btn btn-default btn-sm">EDITER</a>
                        <?php if( ($d->company_type->name == 'company') && ($d->user->active) && ($d->account->allow_card_use) ): ?>
                            <a href="<?= $this->Url->build(['action'=>'accrediter',$d->id]) ?>"  class="btn btn-wj btn-sm">ACCREDITER</a>
                        <?php else: ?>
                            <a href="javascript:void(0)"  class="btn btn-default btn-sm">ACCREDITER</a>
                        <?php endif; ?>
                    </td>



                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
        </div>
    </div>
</div>




<style type="text/css">

    input[type="search"] {

        padding: 8px;

    }

    table.dataTable thead th, table.dataTable thead td {
        padding: 10px 18px;
        border-bottom:none;
    }

</style>


<script>
    $(document).ready(function() {

        var companiesTable = $('#companies').DataTable({
            dom: 'Bfrtip',
            searching : true,

            /* Cacher la colonne de l'identifiant */
            columnDefs: [
                {
                    "targets": [ 0 ],
                    "visible": false,
                    "searchable": false
                }
            ],

            order : [[ 0, "desc" ]],

            language: {
                search: "",
                searchPlaceholder: "Recherche ...",
                processing:     "Traitement en cours...",
                lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
                info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                infoPostFix:    "",
                loadingRecords: "Chargement en cours...",
                zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable:     "Aucune donnée disponible dans le tableau",
                paginate:
                    {
                        next : "Suivant",
                        previous:"Précédent",
                        entries : "entrées",
                        showing : "affichage",
                    }

            }
        });

        $('#companies-search').keyup(function(){
            companiesTable.search($(this).val());
            companiesTable.draw();
        });

        $('#companies_filter').hide();


    });


</script>

plugins/Admin/src/Template/Element/footer.ctp
<footer class="footer text-center"> Proxidesk Dev Test </footer>

plugins/Admin/src/Template/Element/hotels_table.ctp
<div class="row">
    <div class="col-sm-7">
        <h5>HOTELS <span class="label label-table label-info"><?= $data->count() ?></span></h5>
    </div>
    <div class="col-sm-2"></div>
    <div class="col-sm-3 text-right">
        <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn waves-effect btn-wj waves-light btn-info"><i class="fa fa-search"></i></button>
            </span>
            <input type="text" id="companies-search"  class="form-control" placeholder="Chercher ...">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table id="companies" class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>ID UNIQUE</th>
                    <th>DENOMINATION</th>
                    <th class="text-center">COMPTE</th>
                    <th class="text-center">CARTE</th>
                    <th class="text-center">PAIEMENT</th>
                    <th class="text-center">COMMISSION</th>
<!--                    <th class="text-center">REMISE</th>-->
                    <th class="text-right">ACTIONS</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data as $d): ?>
                    <tr>
                        <td>
                            <?= $d->id ?>
                        </td>

                        <!-- ID UNIQUE -->
                        <td  class="text-left">
                            <b><?= h($d->unique_id) ?></b>
                        </td>


                        <td>
                            <a href="<?= $this->Url->build(['action'=>'view',$d->id]) ?>" ><?= h(strtoupper($d->denomination)) ?></a>
                        </td>

                        <!-- Statut Compte ( Connexion ) -->
                        <td class="text-center">
                            <?php if($d->user->active): ?>
                                <i class="fa fa-check-square" aria-hidden="true" style="color: #4caf50"></i>
                            <?php else: ?>
                                <i class="mdi mdi-close-box" style="color: red"></i>
                            <?php endif; ?>
                        </td>

                        <!-- Statut Compte ( Paiement ) -->
                        <td class="text-center">
                            <?php if($d->account->allow_card_use): ?>
                                <i class="fa fa-check-square" aria-hidden="true" style="color: #4caf50"></i>
                            <?php else: ?>
                                <i class="mdi mdi-close-box" style="color: red"></i>
                            <?php endif; ?>
                        </td>

                        <!-- Paiement -->
                        <td  class="text-center">
                            <?php if((int)$d->account->total_to_pay == 0 ) : ?>
                                <span class="label label-success label-rouded">Réglé</span>
                            <?php else: ?>
                                <?= number_format((int)$d->account->total_to_pay, 0, ',', ' ') ?>
                            <?php endif; ?>
                        </td>

                        <!-- COMMISSION -->
                        <td  class="text-center">
                            <?= h((float)$d->commission) ?> %
                        </td>


                        <!-- Actions -->
                        <td class="text-right">
                            <a href="<?= $this->Url->build(['action'=>'login',$d->id]) ?>" target="_self" class="btn btn-wj btn-sm">
                                CONNECTER
                            </a>
                            <a href="<?= $this->Url->build(['action'=>'edit',$d->id]) ?>"  class="btn btn-default btn-sm">EDITER</a>
                        </td>

                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>




<style type="text/css">

    input[type="search"] {

        padding: 8px;

    }

    table.dataTable thead th, table.dataTable thead td {
        padding: 10px 18px;
        border-bottom:none;
    }

</style>


<script>
    $(document).ready(function() {

        var companiesTable = $('#companies').DataTable({
            dom: 'Bfrtip',
            searching : true,

            /* Cacher la colonne de l'identifiant */
            columnDefs: [
                {
                    "targets": [ 0 ],
                    "visible": false,
                    "searchable": false
                }
            ],
            order : [[ 0, "desc" ]],
            language: {
                search: "",
                searchPlaceholder: "Recherche ...",
                processing:     "Traitement en cours...",
                lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
                info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                infoPostFix:    "",
                loadingRecords: "Chargement en cours...",
                zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable:     "Aucune donnée disponible dans le tableau",
                paginate:
                    {
                        next : "Suivant",
                        previous:"Précédent",
                        entries : "entrées",
                        showing : "affichage",
                    }

            }
        });

        $('#companies-search').keyup(function(){
            companiesTable.search($(this).val());
            companiesTable.draw();
        });

        $('#companies_filter').hide();


    });


</script>

plugins/Admin/src/Template/Element/invoices_table.ctp
    <!-- Nouvelle Table -->
    <div class="row">
        <div class="col-sm-7">
            <h5>FACTURES <span class="label label-table label-info"><?= $data->count() ?></span></h5>
        </div>
        <div class="col-sm-2"></div>
        <div class="col-sm-3 text-right">
            <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn waves-effect btn-wj waves-light btn-info"><i class="fa fa-search"></i></button>
            </span>
                <input type="text" id="orders-search"  class="form-control" placeholder="Chercher ...">
            </div>
        </div>
    </div>



    <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
                <table id="orders" class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-left">ID</th>
                        <th class="text-left">REFERENCE</th>
                        <th class="text-left">ENTREPRISE</th>
                        <th class="text-center">STATUT</th>

                        <th class="text-left">DATE</th>

                        <th class="text-right">ACTIONS</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($data as $d): ?>
                        <tr>
                            <td><?= h($d->id) ?></td>
                            <td>
                                <a href="<?= $this->Url->build(['action'=>'view',$d->id]) ?>" ><?= h(strtoupper($d->ref)) ?></a>
                            </td>
                            <td class="text-left">
                                <a href="<?= $this->Url->build(['action'=>'view',$d->id]) ?>" ><?= h(strtoupper($d->company->denomination)) ?></a>
                            </td>
                            <td class="text-center">
                                <?php if($d->status == 'draft'): ?>
                                    <span class="label label-warning label-rouded">BROUILLON</span>
                                <?php elseif($d->status == 'confirmed'): ?>
                                    <span class="label label-success label-rouded">CONFIRME</span>
                                <?php endif; ?>
                            </td>
                            <td><?= h($d->created->i18nFormat('dd/M/Y HH:mm')) ?></td>

                            <!-- Actions -->
                            <td class="text-right">
                                <?php if($d->status == 'pending') : ?>

                                    <a href="<?= $this->Url->build(['action'=>'process',$d->id,'valid']) ?>"  class="btn btn-success btn-sm">Valider</a>
                                    <a href="<?= $this->Url->build(['action'=>'process',$d->id,'canceled']) ?>"  class="btn btn-warning btn-sm">Annuler</a>
                                    <a href="<?= $this->Url->build(['action'=>'process',$d->id,'refused']) ?>"  class="btn btn-danger btn-sm">Refuser</a>

                                <?php else: ?>

                                    <a href="javascript:void(0)"  class="btn btn-default btn-sm">Valider</a>
                                    <a href="javascript:void(0)"  class="btn btn-default btn-sm">Annuler</a>
                                    <a href="javascript:void(0)"  class="btn btn-default btn-sm">Refuser</a>

                                <?php endif; ?>
                            </td>


                        </tr>
                    <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>




    <style type="text/css">

        input[type="search"] {

            padding: 8px;

        }

        table.dataTable thead th, table.dataTable thead td {
            padding: 10px 18px;
            border-bottom:none;
        }

    </style>


    <script>
        $(document).ready(function() {

            var companiesTable = $('#orders').DataTable({
                dom: 'Bfrtip',
                searching : true,

                /* Cacher la colonne de l'identifiant */
                columnDefs: [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }
                ],
                order : [[ 0, "desc" ]],
                language: {
                    search: "",
                    searchPlaceholder: "Recherche ...",
                    processing:     "Traitement en cours...",
                    lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
                    info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                    infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                    infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                    infoPostFix:    "",
                    loadingRecords: "Chargement en cours...",
                    zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                    emptyTable:     "Aucune donnée disponible dans le tableau",
                    paginate:
                        {
                            next : "Suivant",
                            previous:"Précédent",
                            entries : "entrées",
                            showing : "affichage",
                        }

                }
            });

            $('#orders-search').keyup(function(){
                companiesTable.search($(this).val());
                companiesTable.draw();
            });

            $('#orders_filter').hide();


        });


    </script>

plugins/Admin/src/Template/Element/left_menu.ctp
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav">
        <div class="sidebar-head">
            <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu"></span></h3> </div>
        <ul class="nav" id="side-menu">
            <li>
                <a href="<?= $this->Url->build("/admin/dashboard") ?>">
                    <i class="mdi mdi-chart-bar fa-fw"></i><span class="hide-menu">TABLEAU DE BORD</span>
                </a>
            </li>
            <li class="devider"></li>

            <li>
                <a href="<?= $this->Url->build(['controller'=>'companies','action'=>'index','company']) ?>">
                    <i class="mdi mdi-domain"></i><span class="hide-menu">  ENTREPRISES</span>
                </a>
            </li>

            <li>
                <a href="<?= $this->Url->build(['controller'=>'companies','action'=>'index','rbac']) ?>">
                    <i class="mdi mdi-domain"></i><span class="hide-menu">  AUTORISATIONS</span>
                </a>
            </li>


            <li class="devider"></li>
            <li><a href="<?= $this->Url->build(['plugin'=>'authentication','controller'=>'users','action'=>'logout']) ?>"><i class="mdi mdi-logout fa-fw"></i><span class="hide-menu">DECONNEXION</span></a></li>
        </ul>
    </div>
</div>

plugins/Admin/src/Template/Element/main_menu.ctp
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">

        <div class="top-left-part">
            <!-- Logo -->
            <a class="logo" href="<?= $this->Url->build('/') ?>">
                <!-- Logo icon image, you can use font-icon also -->
                <b></b>
                <!-- Logo text image you can use text also -->
                <span class="hidden-xs">

                </span>
            </a>
        </div>

        <!-- /Logo -->
        <ul class="nav navbar-top-links navbar-left">
            <li><a href="javascript:void(0)" class="open-close waves-effect waves-light visible-xs"><i class="ti-close ti-menu"></i></a></li>

        </ul>

        <ul class="nav navbar-top-links navbar-right pull-right">
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
                </a>
            </li>
        </ul>

    </div>
</nav>

plugins/Admin/src/Template/Element/orders_table.ctp
    <!-- Nouvelle Table -->
    <div class="row">
        <div class="col-sm-7">
            <h5>COMMANDES <span class="label label-table label-info"><?= $data->count() ?></span></h5>
        </div>
        <div class="col-sm-2"></div>
        <div class="col-sm-3 text-right">
            <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn waves-effect btn-wj waves-light btn-info"><i class="fa fa-search"></i></button>
            </span>
                <input type="text" id="orders-search"  class="form-control" placeholder="Chercher ...">
            </div>
        </div>
    </div>



    <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
                <table id="orders" class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-left">ID</th>
                        <th class="text-left">REFERENCE</th>
                        <th class="text-left">ENTREPRISE</th>
                        <th class="text-center">STATUT</th>
                        <th class="text-left">CREDITS</th>
                        <th class="text-left">DATE</th>
                        <th class="text-left">LIVRAISON</th>
                        <th class="text-right">ACTIONS</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($data as $d): ?>
                        <tr>
                            <td><?= h($d->id) ?></td>
                            <td>
                                <a href="<?= $this->Url->build(['action'=>'view',$d->id]) ?>" ><?= h(strtoupper($d->ref)) ?></a>
                            </td>
                            <td>
                                <a href="<?= $this->Url->build(['action'=>'view',$d->id]) ?>" ><?= h(strtoupper($d->company->denomination)) ?></a>
                            </td>
                            <td class="text-center">
                                <?php if($d->status == 'pending'): ?>
                                    <span class="label label-warning label-rouded">En attente</span>
                                <?php elseif($d->status == 'valid'): ?>
                                    <span class="label label-success label-rouded">Validé</span>
                                <?php elseif($d->status == 'refused'): ?>
                                    <span class="label label-warning label-rouded">Refusé</span>
                                <?php elseif($d->status == 'canceled'): ?>
                                    <span class="label label-danger label-rouded">Annulé</span>
                                <?php endif; ?>

                            </td>
                            <td>
                                <?= number_format(h($d->total_waps), 0, ',', ' ') ?>
                            </td>
                            <td><?= h($d->created->i18nFormat('dd/M/Y HH:mm')) ?></td>

                            <!-- Date de Livraison souhaitée -->
                            <td><?= h($d->delivery_date->i18nFormat('dd/M/Y')) ?></td>

                            <!-- Actions -->
                            <td class="text-right">
                                <?php if($d->status == 'pending') : ?>

                                    <a href="<?= $this->Url->build(['action'=>'process',$d->id,'valid']) ?>"  class="btn btn-success btn-sm">Valider</a>
                                    <a href="<?= $this->Url->build(['action'=>'process',$d->id,'canceled']) ?>"  class="btn btn-warning btn-sm">Annuler</a>
                                    <a href="<?= $this->Url->build(['action'=>'process',$d->id,'refused']) ?>"  class="btn btn-danger btn-sm">Refuser</a>

                                <?php else: ?>

                                    <a href="javascript:void(0)"  class="btn btn-default btn-sm">Valider</a>
                                    <a href="javascript:void(0)"  class="btn btn-default btn-sm">Annuler</a>
                                    <a href="javascript:void(0)"  class="btn btn-default btn-sm">Refuser</a>

                                <?php endif; ?>
                            </td>


                        </tr>
                    <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>




    <style type="text/css">

        input[type="search"] {

            padding: 8px;

        }

        table.dataTable thead th, table.dataTable thead td {
            padding: 10px 18px;
            border-bottom:none;
        }

    </style>


    <script>
        $(document).ready(function() {

            var companiesTable = $('#orders').DataTable({
                dom: 'Bfrtip',
                searching : true,

                /* Cacher la colonne de l'identifiant */
                columnDefs: [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }
                ],
                order : [[ 0, "desc" ]],
                language: {
                    search: "",
                    searchPlaceholder: "Recherche ...",
                    processing:     "Traitement en cours...",
                    lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
                    info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                    infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                    infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                    infoPostFix:    "",
                    loadingRecords: "Chargement en cours...",
                    zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                    emptyTable:     "Aucune donnée disponible dans le tableau",
                    paginate:
                        {
                            next : "Suivant",
                            previous:"Précédent",
                            entries : "entrées",
                            showing : "affichage",
                        }

                }
            });

            $('#orders-search').keyup(function(){
                companiesTable.search($(this).val());
                companiesTable.draw();
            });

            $('#orders_filter').hide();


        });


    </script>

plugins/Admin/src/Template/Element/purchase_order_history.ctp
<div class="table-responsive">
    <table id="companies" class="table">
        <thead>
        <tr>
            <th>DATE</th>
            <th>Quantité</th>
            <th>Etat</th>
            <th>Remarques</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($data as $d): ?>
            <tr>
                <td><?= h($d->created) ?></td>
                <td><?= h($d->qty) ?></td>
                <td>
                    <?php if($d->status == 'pending'): ?>
                      <span class="label label-warning label-rouded">En attente</span>
                    <?php elseif($d->status == 'valid'): ?>
                      <span class="label label-warning label-rouded">Validé</span>
                    <?php elseif($d->status == 'refused'): ?>
                      <span class="label label-warning label-rouded">Refusé</span>
                    <?php elseif($d->status == 'canceled'): ?>
                      <span class="label label-warning label-rouded">Annulé</span>
                    <?php endif; ?>
                </td>
                <td><?= h($d->remarks) ?></td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>